# src/agents/sql_agent.py

from src.utils.llm import llm

from src.data.schema_service import get_database_schema
from src.data.query_service import run_query

from src.core.logger import get_logger


# --------------------------------------------------
# Logger
# --------------------------------------------------

logger = get_logger(__name__)


# --------------------------------------------------
# Clean SQL generated by LLM
# --------------------------------------------------

def clean_sql(response_text: str) -> str:
    """
    Remove markdown, prefixes, and extra text
    returned by the LLM.
    """

    if not response_text:
        return ""

    sql = response_text.strip()

    # Remove markdown code blocks
    sql = (
        sql
        .replace("```sql", "")
        .replace("```SQL", "")
        .replace("```", "")
        .strip()
    )

    # Remove SQL: prefix
    if sql.upper().startswith("SQL:"):
        sql = sql[4:].strip()

    # Find actual SQL starting point
    upper_sql = sql.upper()

    select_pos = upper_sql.find("SELECT")
    with_pos = upper_sql.find("WITH")

    positions = [
        pos
        for pos in [select_pos, with_pos]
        if pos >= 0
    ]

    if positions:
        sql = sql[min(positions):]

    # Keep only the first SQL statement
    if ";" in sql:
        sql = sql.split(";", 1)[0] + ";"

    return sql.strip()


# --------------------------------------------------
# Validate generated SQL structure
# --------------------------------------------------

def validate_generated_sql(sql_query: str) -> None:
    """
    Perform basic validation before sending
    the query to the execution layer.

    query_service.py will still perform the
    main read-only security validation.
    """

    if not sql_query:
        raise ValueError(
            "LLM returned an empty SQL query."
        )

    cleaned = sql_query.strip().upper()

    # Only read-only query types are allowed
    if not (
        cleaned.startswith("SELECT")
        or cleaned.startswith("WITH")
    ):
        raise ValueError(
            "Generated query is not a SELECT/WITH query."
        )


# --------------------------------------------------
# Generate SQL from user question
# --------------------------------------------------

def generate_sql(question: str) -> str:
    """
    Convert a natural-language business question
    into PostgreSQL SQL.
    """

    logger.info(
        "Starting natural-language to SQL generation"
    )

    # Read live PostgreSQL schema
    schema = get_database_schema()

    prompt = f"""
You are an expert PostgreSQL data analyst
working for an insurance company.

Convert the user's question into exactly ONE
correct PostgreSQL query.

DATABASE SCHEMA:

{schema}

STRICT RULES:

1. Use only tables and columns present in the schema.
2. Generate only SELECT or WITH queries.
3. Never generate INSERT, UPDATE, DELETE, DROP,
   ALTER, TRUNCATE, CREATE, GRANT or REVOKE.
4. Use correct foreign-key relationships for JOINs.
5. Never invent tables or columns.
6. Use valid PostgreSQL syntax.
7. Use ORDER BY and LIMIT for ranking questions.
8. Use meaningful aliases for aggregate columns.
9. Do not return explanations.
10. Do not return markdown.
11. Return exactly one SQL query.
12. Avoid SELECT * when specific columns can be used.
13. Use aggregation only when required by the question.

USER QUESTION:

{question}
"""

    response = llm.invoke(prompt)

    sql_query = clean_sql(
        response.content
    )

    validate_generated_sql(
        sql_query
    )

    logger.info(
        "SQL query generated successfully"
    )

    # Useful in development.
    # Avoid logging query text if it may contain
    # sensitive data in production.
    logger.debug(
        f"Generated SQL: {sql_query}"
    )

    return sql_query


# --------------------------------------------------
# Remove hallucinated currency symbols
# --------------------------------------------------

def sanitize_answer(
    answer: str,
    question: str
) -> str:
    """
    Remove currency symbols when the user
    did not explicitly specify a currency.
    """

    question_lower = question.lower()

    currency_terms = [
        "$",
        "usd",
        "dollar",
        "dollars",

        "₹",
        "inr",
        "rupee",
        "rupees",

        "€",
        "eur",
        "euro",
        "euros",

        "£",
        "gbp",
        "pound",
        "pounds"
    ]

    currency_given = any(
        term in question_lower
        for term in currency_terms
    )

    if not currency_given:
        answer = (
            answer
            .replace("$", "")
            .replace("₹", "")
            .replace("€", "")
            .replace("£", "")
        )

    return answer.strip()


# --------------------------------------------------
# Generate natural-language answer
# --------------------------------------------------

def generate_answer(
    question: str,
    sql_query: str,
    rows: list
) -> str:
    """
    Convert raw PostgreSQL results into a
    business-friendly natural-language answer.
    """

    # Do not waste another LLM request
    # if database returned nothing
    if not rows:
        return "No matching data was found."

    # Limit amount of data sent to LLM
    limited_rows = rows[:20]

    prompt = f"""
You are an insurance data analyst.

Answer the user's question using ONLY
the SQL results provided below.

USER QUESTION:
{question}

SQL QUERY:
{sql_query}

SQL RESULTS:
{limited_rows}

STRICT RULES:

1. Use only the supplied SQL results.
2. Never invent numbers or facts.
3. Keep the response concise and clear.
4. Mention the important values.
5. Use business-friendly language.
6. Do not mention that you are an AI.
7. Return only the final answer.
8. Currency is UNKNOWN unless the user
   explicitly specified one.
9. NEVER add $, ₹, €, £, USD, INR, EUR,
   GBP, or any other currency unless the
   user explicitly mentioned it.
10. You may format large numbers using
    thousand, million, or billion.
"""

    response = llm.invoke(prompt)

    answer = response.content.strip()

    answer = sanitize_answer(
        answer=answer,
        question=question
    )

    return answer


# --------------------------------------------------
# Complete SQL Agent
# --------------------------------------------------

def ask_sql_agent(question: str) -> dict:
    """
    Complete SQL Agent pipeline:

    User question
        -> LLM SQL generation
        -> SQL validation
        -> PostgreSQL execution
        -> Natural-language answer
    """

    logger.info(
        "SQL Agent request received"
    )

    try:

        # ------------------------------------------
        # Step 1: Generate SQL
        # ------------------------------------------

        sql_query = generate_sql(
            question
        )


        # ------------------------------------------
        # Step 2: Execute SQL
        # ------------------------------------------

        logger.info(
            "Executing generated SQL query"
        )

        rows = run_query(
            sql_query
        )

        logger.info(
            f"SQL execution successful. "
            f"Rows returned: {len(rows)}"
        )


        # ------------------------------------------
        # Step 3: Generate final answer
        # ------------------------------------------

        answer = generate_answer(
            question=question,
            sql_query=sql_query,
            rows=rows
        )

        logger.info(
            "SQL Agent completed successfully"
        )


        # ------------------------------------------
        # Final success response
        # ------------------------------------------

        return {
            "status": "success",
            "agent": "sql",
            "question": question,
            "sql": sql_query,
            "row_count": len(rows),
            "results": rows,
            "answer": answer
        }


    # --------------------------------------------------
    # Controlled Error Handling
    # --------------------------------------------------

    except Exception as exc:

        logger.exception(
            "SQL Agent execution failed"
        )

        return {
            "status": "error",
            "agent": "sql",
            "question": question,
            "error": str(exc)
        }


# --------------------------------------------------
# Local Test
# --------------------------------------------------

if __name__ == "__main__":

    test_question = (
        "Show top 5 policy types "
        "by total annual premium"
    )

    result = ask_sql_agent(
        test_question
    )

    print("\nSQL Agent Result:")
    print(result)